# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

r_packages:
  - leaflet

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - sudo ldconfig

after_success:
    - Rscript -e 'covr::codecov()'
